name: "0.1$(Rev:.r)"

pool:
  vmImage: "windows-latest"

variables:
  CI: "true"
  isMaster: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]
  solution: "sql-generator.sln"
  buildPlatform: "Any CPU"
  buildConfiguration: "Release"

steps:
  - task: UseDotNet@2
    displayName: Install .NET 5.0.x
    inputs:
      packageType: "sdk"
      version: "5.0.x"
  # Needed for SonarQube
  - task: UseDotNet@2
    displayName: Install .NET Core 2.2.x for SonarCloud
    inputs:
      packageType: "sdk"
      version: "2.2.x"
  - task: SonarCloudPrepare@1
    displayName: Prepare SonarCloud Analysis
    inputs:
      SonarCloud: "SonarCloud"
      organization: "jacksondr5"
      scannerMode: "MSBuild"
      projectKey: "01ffbbe9f7191614102d37f67c1148aedb773cb9"
      projectName: "sql-generator"
      projectVersion: $(Build.BuildNumber)
      extraProperties: |
        sonar.coverage.exclusions=**/ConsoleApp/**
  - task: DotNetCoreCLI@2
    displayName: Restore Packages
    inputs:
      command: "restore"
      projects: $(solution)
      feedsToUse: "select"
      verbosityRestore: "Normal"
  - task: DotNetCoreCLI@2
    displayName: Build Solution
    inputs:
      command: "build"
      projects: $(solution)
      arguments: "-c $(buildConfiguration) --no-restore --nologo"
  - task: DotNetCoreCLI@2
    displayName: Run Unit Tests
    inputs:
      command: "test"
      projects: $(solution)
      arguments: "--nologo --no-build -c $(buildConfiguration) -s ./UnitTest.runsettings"
  - task: DotNetCoreCLI@2
    displayName: Create NuGet Package
    inputs:
      command: "pack"
      packagesToPack: "ConsoleApp/ConsoleApp.csproj"
      nobuild: true
      versioningScheme: "byBuildNumber"
      verbosityPack: "Normal"
  - task: SonarCloudAnalyze@1
    displayName: Run SonarCloud Analysis
  - task: SonarCloudPublish@1
    displayName: Publish SonarCloud Analysis
    inputs:
      pollingTimeoutSec: "300"
  - task: DotNetCoreCLI@2
    displayName: Push NuGet Package to NuGet
    inputs:
      command: "custom"
      custom: "nuget"
      arguments: >
        push $(Build.ArtifactStagingDirectory)\*.nupkg
        -s https://api.nuget.org/v3/index.json
        -k $(NugetApiKey)
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
